spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: J9AHJQ7501TIZGFF3JWA
  secretKey: LqqIwYbeVlZqjv+LZovE/RuQRCLvM3BYIaXVlGrf
  bucketName: moviefun
#
#
#  AccessKey: J9AHJQ7501TIZGFF3JWA
#  SecretKey: LqqIwYbeVlZqjv+LZovE/RuQRCLvM3BYIaXVlGrf
#  Region:    us-east-1
#  SQS ARNs:  <none>